### ISSUE TITLE
gmsh error(floating point exception)

### ISSUE THREAD

**Issue by brandanli** [HomerReid/scuff-em#134]
Thanks for your work and I have installed the SCUFF-em successfully. But there was another trouble when I tried to verified the examples. 
1 Could not open file xxxxtransformed.pp
2 gmsh error (floating point exception)
![gmsh error](https://cloud.githubusercontent.com/assets/26019623/23576931/cd126652-00ec-11e7-8240-b99bed9cff2b.jpg)

**Comment by HomerReid** [comment]
Based on your screenshot, it appears you are running the codes from within the directory `/usr/local/share/scuff-em/examples/CubeTorus`. This is a system directory, not a user directory, and you almost certainly do not have write access to this directory, which is why the code is unable to create the output file you mentioned. The solution is simply to run the code from within your own user filespace.

I can't debug why gmsh is failing on your system, as I am not a developer or maintainer of gmsh. 

Feel free to ask more questions, or close the issue if satisfied.
