### ISSUE TITLE
incorrect values of reflection/transmission for plane geometry

### ISSUE THREAD

**Issue by shastrirahul** [HomerReid/scuff-em#157]
[files.zip](https://github.com/HomerReid/scuff-em/files/1452948/files.zip)

[files.zip](https://github.com/HomerReid/scuff-em/files/1452947/files.zip)
I am trying to reproduce simple given example of thinfilms. I am getting below output

0.01  0.000000e+00   8.034651e-01  -8.034653e-01

Here the 4th column supposed to give reflection but it is giving a **negative** value which is incorrect. I have attached the required files that i have used. 

My future aim is to compute reflection/transmission/absorption  using scuff-transmission for the gold infinite mirror. Looking forward to your reply.

**Comment by HomerReid** [comment]
Thanks for the bug report. This is not actually a bug in the code, but rather a case of out-of-date documentation---the output-file format has changed since I wrote the scuff-transmission tutorials, and I haven't updated it yet. I will do that, but in the meantime you can look at the preamble of the output file to see what is being reported on what line:

````
# scuff-transmission run on reynolds-CELSIUS-R920 (11/08/17::12:25:31)
# data file columns: 
# 1:      omega 
# 2:      theta (incident angle) (theta=0 --> normal incidence)
# 3:      upward   flux / vacuum plane-wave flux (TE)
# 4:      downward flux / vacuum plane-wave flux (TE)
# 5:      upward   flux / vacuum plane-wave flux (TM)
# 6:      downward flux / vacuum plane-wave flux (TM)
# 
# 7,8:    mag, phase a_Upper(TE -> TE)
# 9,10:   mag, phase a_Upper(TE -> TM)
# 11,12   mag, phase a_Upper(TM -> TE)
# 13,14   mag, phase a_Upper(TM -> TM)
# 15,16   mag, phase a_Lower(TE -> TE)
# 17,18   mag, phase a_Lower(TE -> TM)
# 19,20   mag, phase a_Lower(TM -> TE)
# 21,22   mag, phase a_Lower(TM -> TM)
````

As you see, the fourth column is reporting downward-traveling flux, which is why there's a minus sign.

You probably want to plot the transmission and reflection coefficients, which are columns 7 and 15, i.e. in gnuplot you could do

````
gnuplot> plot 'ThinFilm_58.transmission' u 1:7, '' u 1:15 
````

This produces a plot like this:

![trvw](https://user-images.githubusercontent.com/920123/32585513-c5b6f082-c4cb-11e7-866c-fd6a1a8309ee.png)

**Comment by shastrirahul** [comment]
Thank you for clearing the doubt!! The problem is solved!

**Comment by shastrirahul** [comment]
Hello,

Thank you for resolving the above issue. Now I am trying geometry
consisting of infinite Au mirror with Au sphere separated by some gap. I
computing the reflectance coefficient but it is not giving the correct
answer (checked with cst). All the files are attached below. Can you look
into this matter ASAP. Thank you again for helping.

Regards


‌
