### ISSUE TITLE
Python integration using intel distribution. 

### ISSUE THREAD

**Issue by CCherqui** [HomerReid/scuff-em#178]
I'm using the Intel optimized distribution of anaconda [https://software.intel.com/en-us/distribution-for-python](url) to compile `scuff-em`. It compiles fine but sticks the packages and libraries in `/usr/local/lib/python2.7/site-packages` instead of where the intel python distribution lives `/opt/intel/intelpython2/lib`

To be clear, it is using intel python to compile ([config.log](https://github.com/HomerReid/scuff-em/files/2186105/config.log), but the install is putting the scuff python libs in the folder for the python installation that comes standard on a mac. This makes is so python won't find the right files when I try to `import scuff`.  

I've "fixed" the problem by copying them into the right folder so that `import scufff` works but is there a way to direct the install to the right folder in the configure stage? 

also, does it matter if I use Python 2 or can I use python 3?

**Comment by HomerReid** [comment]
I'm not aware of a way to instruct the autotools to put python libraries and only those libraries in a particular place. There may be an environment variable or `--configure` option for this, although I don't see one documented on the Autotools website. In principle the SCUFF-EM build infrastructure could be specialized to accommodate this if it were a common problem affecting multiple users.

For now, would it work for you to set `PYTHONPATH` before invoking python? e.g. 

```
PYTHONPATH=/usr/local/lib/python2.7/site-packages python scuffScript.py
```

or

```
export PYTHONPATH=/usr/local/lib/python2.7/site-packages
python scuffScript.py
```

This way you wouldn't need to remember to copy the files after each SCUFF rebuild. Another option that would achieve the same end would be to make soft links instead of copies, i.e.

```
% ln -s /usr/local/lib/python2.7/site-packages/scuff.*  /opt/intel/intelpython2/lib
```

> also, does it matter if I use Python 2 or can I use python 3?

I'm not aware of anything that depends on python 2 vs. 3. If you come across anything, please file an issue---it should be quickly fixable.

**Comment by CCherqui** [comment]
Ok, that works. I'll close this one up. I'll go back to Python 3.7 and if I come across anything I'll open up an issue.
