### ISSUE TITLE
Non-rectangular 2D lattices not yet supported ?

### ISSUE THREAD

**Issue by CCherqui** [HomerReid/scuff-em#179]
So I've been working up to doing a triangular lattice of Ag nanodisks, when I built the lattice and tried it I got `error: non-rectangular 2D lattices not yet supported (aborting)`.

Is there a timeline for this feature to be implemented?

**Comment by HomerReid** [comment]
No, at the moment there are several other things taking precedence over this, and you're the first person to ask for it, so I can't consider it a high priority---especially in the absence of any evidence that it will be particularly useful, or allow studies of systems that couldn't be done with other methods, or lead to high-impact publications, or otherwise justify the considerable expenditure of time it would require to implement. 

But if you can furnish such evidence and would be willing to help with testing, let me know!

**Comment by CCherqui** [comment]
I certainly can, should I post such evidence in this issue thread?

**Comment by HomerReid** [comment]
Sure, please describe what you have in mind. As a warmup for the case of non-rectangular lattices, is there any interesting calculation that can be done for rectangular lattices, or non-periodic geometries describing finite supercells of non-rectangular lattices? Note that, for something like Ag nanodiscs, it should be possible to do calculations involving thousands of unit cells, as in [this example](https://homerreid.github.io/SCUFFEMTutorialSymposium/SpiralArrays/). Before discussing the possibility of adding new features it would be good to understand what can be done with the existing code and exactly why the new feature is required.

**Comment by CCherqui** [comment]
Yes, that's a good idea. Let me explore these large array examples first and see if this gets me to where I want to be.
