### ISSUE TITLE
Above 1 transmission for cube/sphere array

### ISSUE THREAD

**Issue by tongmuyao** [HomerReid/scuff-em#23]
When using scuff-transmission to get the transmission coefficient of a nanocube/nanosphere array at normal incidence (into the screen),  output file contains >1 transmission within the visible wavelenths. 

![qq 20150121224202](https://cloud.githubusercontent.com/assets/10646820/5850202/cfb81d00-a1be-11e4-8978-109603edeeac.png)

The scuffgeo file is very simple

LATTICE
   VECTOR 0.1 0
   VECTOR 0 0.1
ENDLATTICE

REGION Exterior MATERIAL CONST_EPS_2

OBJECT Sphere
     MESHFILE Sphere.msh
     MATERIAL SILICON
ENDOBJECT

**Comment by HomerReid** [comment]
Fixed in 36f39b022b0f324521a99c946a5eae8c04ac1894.

The difficulty was just one of normalization when the exterior medium is non-vacuum (as in this case, where the exterior medium had Epsilon=2). The transmitted flux was being computed correctly, but the *incident* flux was being computed incorrectly (I had been using the expression for the incident flux of a plane wave in vacuum, failing to account for the non-unity relative wave impedance of a dielectric medium.)

Thanks for the bug report -- please confirm that your calculation yields correct results now.

**Comment by tongmuyao** [comment]
Hi Homer,

Thanks for the bug report. Have you update the version in ab-initio?

2015-01-24 14:41 GMT-05:00 HomerReid <notifications@github.com>:

**Comment by HomerReid** [comment]
Please confirm that the calculation yields correct results and reopen the issue if not.
