### ISSUE TITLE
scuff-tmatrix fails to reproduce Mie coefficients for a dielectric sphere

### ISSUE THREAD

**Issue by ETomlinson** [HomerReid/scuff-em#26]
I could not get scuff-tmatrix to correctly compute the well-known diagonal T-Matrix elements for a dielectric sphere. I tried with a fairly fine spherical mesh (~3500 panels), a range of different frequencies (0.001 - 10.0), and both a real and complex permittivity.

**Comment by HomerReid** [comment]
Should be fixed in fd25c17ffb36049d19e7a42aafd7df1255860336. 

The difficulty was that the hard-coded vector spherical wavefunctions in GetMNlmHardCoded (src/libs/libSpherical.cc) were only correctly implemented for the outgoing waves (WaveType==LS_OUTGOING), not the regular or incoming waves. I am still unsure what went wrong, but a reasonable fix is to switch back to the non-hardcoded version of the function (GetMNlm) that uses the AmosBessel library to compute spherical Bessel and Hankel functions.

Thanks for the bug report. Please confirm that the fix is properly implemented and close the issue when satisfied!

**Comment by ETomlinson** [comment]
I have tested the new implementation and it seems that the T-Matrix coefficients are off by a phase factor of i. When I multiply the T-Matrix by i I get agreement with the Mie coefficients.

**Comment by HomerReid** [comment]
This is now fixed in 8ff57e054dc999527210e67d916f8be4191c7178.

Thanks for the bug report, and please verify and close the issue if satisfied.
