### ISSUE TITLE
Compilation python interface

### ISSUE THREAD

**Issue by jmllorens** [HomerReid/scuff-em#31]
During the compilation of the scuff_em, I got an error saying that there is no rule for scuff-python.cpp. The way to fix the problem is uncommenting the two last lines of the Makefile in src/lib/python:

    ##############################################################################
    # Generate wrappers via SWIG:

    scuff-python.cpp scuff.py: $(SWIG_SRC) $(top_srcdir)/src/libs/libscuff/libscuff.h     $(top_srcdir)/src/libs/libscuff/GTransformation.h $(top_srcdir)/src/libs/libIncField/libIncField.h $(top_srcdir)/src/libs/libhrutil/libhrutil.h $(top_srcdir)/src/libs/libMatProp/libMatProp.h $(top_srcdir)/src/libs/libhmat/libhmat.h
    swig -Wall $(AM_CPPFLAGS) -outdir $(builddir) -c++ -python -o $(builddir)/scuff-python.cpp scuff.i

    # Tell versions [3.59,3.63) of GNU make to not export all variables.
    # Otherwise a system limit (for SysV at least) may be exceeded.

I haven't trace back the problem origin, but these two lines appear commented after running autogen.sh and configure.

**Comment by jmllorens** [comment]
Posted just in case someone could benefit of this fix.

**Comment by HomerReid** [comment]
Thanks. The python interface seems to cause a lot of compilation difficulties, and I have considered removing it from the code, or at least disabling it by default. I'm not a python user myself, and I would appreciate feedback from anybody who uses the SCUFF python interface -- what do you do with it? Do you find it useful?

**Comment by jfeist** [comment]
Hi Homer,
I use the python interface quite a bit, and I do find it very useful. There are a few main reasons:

1. It allows me do "custom" codes very quickly and easily. For example, I've had a few cases where I wanted to calculate the Green's function between pairs of points, so I wrote a small python script that calculates the BEM matrix, factorizes it, and then reuses it many times to solve for KN with a point dipole at different positions, and calculating the resulting EM field at other positions. AFAIK, there's no "native" scuff-em code that does this, and using, e.g., scuff-scatter would mean recalculating the BEM matrix for every dipole position, and would be a bit of a pain to set up the inputs every time and extract the information in the way I need it.
2. It allows me to work interactively, e.g., through the [IPython notebook](http://ipython.org/notebook.html). One example for a concrete use case: For the case above (calculating Green's functions), the thing that takes a long time is to calculate and factorize the BEM matrix. I wrote a small python script that does only this and saves the factorized matrix to disk. I submitted this script (with a few different parameters) to the batch queue on a cluster. Then I could connect to an IPython Notebook server I have running on the head node on the cluster, load the factorized BEM matrix, and use it to get the GF interactively for a few points to "explore" the structure. 
3. The rich ecosystem of libraries is very useful. For example, in python (especially useful when working interactively), I can directly use, e.g., matplotlib to plot the results, and then try different parameters and plot again, instead of having to write them to disk and then load the data into a plotting program.
4. Python is very flexible, which helps for making scripts that do more than a "normal" scuff program. For example, I have many scripts where I write the .geo file for GMSH based on input parameters, call GMSH from within the script to generate the .msh files, write the .scuffgeo files using these msh files, and then directly load them into scuff, and do the calculation I want. It's nice to have this all integrated - for example, in a case of two identical spheres where I want to vary the radius but keep the distance between the spheres constant, I also need to know the radius to add a "DISPLACEMENT" statement in the .scuffgeo file. That's trivial if everything is within one script.

Of course, many of the use cases I mention above could be done with C++ programs as well, but with python the code is often more concise and needs a lot less "boilerplate", which means I am usually a lot faster and need to do less debugging. That's especially important for the "write once, use once" cases, where writing the code is a significant part of the time taken. And the interactive use and integrated plotting etc is only really possible in python.

So I strongly vote for keeping the python interface!

**Comment by gevero** [comment]
I am also a faithful user of the python interface. For me the main reason is the interactive workflow of the ipython notebook, beside of course the streamlined scripting. So one more convinced vote for the python interface.

Best

Giovanni

**Comment by jmllorens** [comment]
I haven't tried it yet, but I make an extensive use of python in combination with other software, so I would vote for keeping it even if it's a bit painful to maintain. I really amazed of the sort of things that jfeist can do with the interface. I would suggest to add a short tutorial on this in the web page or somewhere.

All best,

Jose.

**Comment by HomerReid** [comment]
Thanks to all who commented. Obviously, the python interface will stay! Glad to know it is useful.
