### ISSUE TITLE
Problem with .SIFlux output files from scuff-neq

### ISSUE THREAD

**Issue by ETomlinson** [HomerReid/scuff-em#36]
The .SIFlux output file from a frequency-integrated scuff-neq run contains an entry for every frequency the adaptive integrator tries, even if they weren't used in the computation. These entries should be omitted from the .SIFlux output file so it represents the actual integral being performed.

**Comment by HomerReid** [comment]
The .SIFlux output file is designed to be a record of all data collected thus far. The information you are looking for is actually contained in a different log file, the .ICFLog file.

It is true that the built-in adaptive integrator doesn't make use of every frequency point it samples. (This is because in some cases it must re-evaluate the integral over a subregion, and in this case it discards its previous samples for that subregion in favor of a new, denser, set of samples. In a perfect world this new denser set would be a superset of the previous sparse set, but the vagaries of numerical quadrature methods generally ensure that this is not possible.) However, the discarded samples still represent useful and costly-to-obtain information about the integrand, which may be useful for a variety of purposes---for example, if we wish to go back and recreate the integrand via some sort of interpolation procedure, in which case it will be helpful to have all the information we can. The .SIFlux output file is designed to store this information.

On the other hand, information about which samples are used and which are discarded by the adaptive integrator may be gleaned from the adaptive integrator's log file, which is the .ICFLog file. ("ICF" stands for "Integrate Cliff Functinon."
