### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by ans18** [HomerReid/scuff-em#39]
Dear Homer, 

building scuff-em exits with an error in my case:

I cloned the current git repo. I do 
`./autogen.sh --prefix=${HOME}/progz/scuff-em-built`
(output look good to me)
then `sudo make install`. After a few minutes of compiling, these are the last lines when `make` exits:

...
`scuff-python.cpp: At global scope:`
`scuff-python.cpp:3556:13: warning: 'void EHFunc_python(const double*, void*, cdouble*)' defined but not used [-Wunused-function]`
`static void EHFunc_python(const double R[3], void *f, cdouble EH[6]) {`
                    ` ^`
`make[4]: *** [_scuff_la-scuff-python.lo] Error 1`
`make[4]: Leaving directory '/home/alex/progz/scuff-em/src/libs/python'`
`make[3]: *** [install] Error 2`
`make[3]: Leaving directory '/home/alex/progz/scuff-em/src/libs/python'`
`make[2]: *** [install-recursive] Error 1`
`make[2]: Leaving directory '/home/alex/progz/scuff-em/src/libs'`
`make[1]: *** [install-recursive] Error 1`
`make[1]: Leaving directory '/home/alex/progz/scuff-em/src'`
`make: *** [install-recursive] Error 1`
`./autogen.sh --prefix=${HOME}/progz/scuff-em-built`

I am on a Ubuntu 14.04 machine.
Can you help me on this? Sorry, if this is a simple issue, I am not very familiar with compiling....

Best regards, 
Alex

**Comment by jfeist** [comment]
Hi Alex,
I believe this will be fixed by a pull request I just submitted (#41). 

BTW, note that your output snippet does not actually show the error, it's just a warning. Unfortunately, compiling `scuff-python.cpp` gives a _huge_ list of warnings, and the error is usually all the way on top. When I get an error, I usually run `make 2>&1 | less`, which pipes both normal and error output from make to less. In less, you can search for the actual error message (`/error` + Enter).

In the current case, you would have found (if it was the same error I got)
```cpp
scuff-python.cpp(5548): error: more than one instance of overloaded function "VecScale" matches the argument list:
            function "VecScale(double *, double, int)"
            function "scuff::VecScale(double *, double)"
            argument types are: (double *, double)
    VecScale(arg1,arg2);
```

Best,
Johannes

**Comment by HomerReid** [comment]
Hi Johannes,

Many thanks for taking the time to fix these errors, which are 100% my fault, and which I failed to notice because I routinely disable the python compilation on my machines (a bad habit, obviously, since it blinds me to cases in which various minor mistakes prevent the python compilation but don't show up in the C++ compilation, or at least don't block that compilation).

Alex: Thanks for your bug report. Can you confirm that Johannes' fix (which I have now merged into the main repository) solves your problem? If so, please close this issue. (If not, let us know by posting whatever error messages you get, following Johannes' suggestion for filtering the output).

Thanks to both for your contribution!

**Comment by jfeist** [comment]
Hi Homer,

don't worry - as I'm one of the people really using the python interface, I'm happy to help out a bit from time to time. Especially considering how much scuff-em has helped us in our research already!

BTW, as you probably saw, I managed to set up Travis CI (#42), so if you merge that, you can check that everything still builds. I included the python interface in there. Really making this useful might require that you also do all your (non-trivial) code changes in separate branches and possibly merge them through pull requests. The pull requests then include an automatic section where travis informs you of the status of the build (see e.g. https://github.com/jfeist/scuff-em/pull/1).

**Comment by ans18** [comment]
Hi Homer & Johannes, 

thanks so much for your help! Johannes' fix did solve the problem, make now runs through. 
Best regards, 
Alex

**Comment by jingli52316** [comment]
Hello, I am a new user of scuff-em, and I have lots of problems to install it. When I do this: sh autogen.sh --prefix=/home/scuff, it stopped with errors:
checking hdf5.h usability... no
checking hdf5.h presence... no
checking for hdf5.h... no
checking H5pubconf.h usability... no
checking H5pubconf.h presence... no
checking for H5pubconf.h... no
configure: error: couldn't find HDF5; configure --without-hdf5
But I indeed have installed the HDF5, then I tried: sh autogen.sh --prefix=/home/scuff --without-hdf5
It works and I got these:
configure: ** The configure process was successful.
configure: ** Now type 'make' to compile and sudo 'make install'.
Next I tried to make and make check, I got troubles again:
FAIL: unit-test-BEMMatrix
../test-driver: line 107:  7588 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: unit-test-PPIs


============================================================================
Testsuite summary for scuff-em 0.95
============================================================================
# TOTAL: 3
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See unitTests/test-suite.log
Please report to homer@homerreid.com
============================================================================
Makefile:734: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/jingli/scuff-em/unitTests'
Makefile:840: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/jingli/scuff-em/unitTests'
Makefile:927: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/jingli/scuff-em/unitTests'
Makefile:421: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
Anyway, I do the make install, the I found when I try to run some test examples,
the command gmsh works, but scuff-analyze, and scuff-scatter, scuff-cas3D.....those commands could not found. So, it is because I did not install the scuff-em successfully? I am on a Ubuntu 15.04.
Can you help me on this? Thanks a lot.

Best regards,
Jing
