### ISSUE TITLE
scuff-transmission does not reproduce the simple ThinFilm example

### ISSUE THREAD

**Issue by AndreasFranz57** [HomerReid/scuff-em#40]
Dear Homer,

trying to reproduce the simple ThinFilm example with ThinFilm_58.scuffgeo of your home page fails with the actual version of SCUFF-EM. 
The exact value of transmitted (reflected) flux is 0.8037232716 (0.1962767283) for w=0.01. In an older version (10/29/2014) I got 0.8059 (0.1921), but I had to use negative frequencies w=-0.01 (?) Ok, not so bad! 
But the actual version gives 2.5e-5 (1.6e-4), which is not only completely wrong but even not conserving energy.
Trying the actual SCUFF-EM with the old (10/29/2014) version of AssembleBEMMatrix.cc file gives the very accurate result 0.8037 (0.1963)! (Using negative frequencies as usual)
The old and the actual version of AssembleBEMMatrix.cc don't seem to be fundamentally different (just some reordering of code), but the result is completely different.
I try to use SCUFF-EM under Cygwin or even ported to Windows Visual Studio, giving both the same results.

Andreas

**Comment by HomerReid** [comment]
Hi Andreas,

Thanks for this important and helpful bug report. I think the problem lies in the scuff-transmission application code, not the core library, and I am looking into it. (Actually, scuff-transmission has been undergoing an overhaul anyway as I switch over to an alternative technique for computing the transmission coefficients, so this is a good spur to that effort.) I believe I will be able to fix the problem by the end of this week.

Thanks again for the bug report!

**Comment by HomerReid** [comment]
This is fixed in c8bed6e08af5c83a3e468eef84e4d83240065ca1. The difficulty was caused by a regression I introduced last month and failed to catch because I don't have good unit tests (but thanks to Johannes that shortcoming will soon be remedied!) 

In the course of fixing this problem I took the opportunity to make some changes to scuff-transmission that I had been meaning to implement. These include a new method for calculating the transmission and reflection coefficients directly from the surface currents (see http://homerreid.com/scuff-em/scuff-transmission2.pdf) which complements the existing technique of computing the upward-traveling and downward-traveling Poynting flux, and also the ability to have the plane wave impinge from above the structure instead of below. I haven't documented this stuff yet, but the output file produced by running the code includes a text description of how to interpret its contents.

Please try it out and close the issue if this fixes your problem.

**Comment by AndreasFranz57** [comment]
Hi Homer,
thank you for fixing this. Still using negative frequencies (?) a thin film is reasonably calculated even for absorbing media (if choosing the right sign for the imaginary part of eps(w)...). 
The output might be somehow misleading because it shows the total flux, which is ok for the transmission t, but instead of the pure reflection r the output gives r-1.
So this is now the starting point for more serious grating calculations.

Thank you.

**Comment by HomerReid** [comment]
Thanks for checking this. I don't understand why you need to use negative frequencies. Is it possible that there is a mixup regarding the physics vs. engineering convention for the frequency, i.e. exp(-i*omega*t) vs exp(+j*omega*t)? If you post the input files (.scuffgeo files, .msh files, command-line arguments, etc) I could take a look.

**Comment by AndreasFranz57** [comment]
Well, after the last modifications you made and with the original ThinFilm_58.scuffgeo file
   scuff-transmission.exe –geometry ThinFilm_58.scuffgeo –Omega -0.01 –ZAbove 2 –ZBelow -1
gives in ThinFilm_58.transmission
   -0.01 0.000000e+000 8.037229e-001 -8.037229e-001 8.037229e-001 -8.037229e-001 ...
which is quite good as the exact result is: 
   Transmission = 0.8037232716
   Reflection   = 0.1962767283 (= 1-0.8037232716)

With
   scuff-transmission.exe –geometry ThinFilm_58.scuffgeo –Omega 0.01 –ZAbove 2 –ZBelow -1
I get
   0.01 0.000000e+000 -1.978152e-013 -2.037591e-013 -1.979188e-013 -3.8555537e-013 ...
which is senseless.

Hopefully this helps.

**Comment by HomerReid** [comment]
I assume this is a Windows-related issue, because I'm not able to reproduce it on my Linux machine. I get correct results for both Omega=0.01 and Omega=-0.01 (for the lossless medium described in the original ThinFIlm_58.scuffgeo file). 

Thanks to anyone who might be able to shed light on this weird Windows behavior.
