### ISSUE TITLE
SiliconBeams example in wiki 

### ISSUE THREAD

**Issue by cyhng** [HomerReid/scuff-em#95]
We run your 1D periodic SiliconBeams from wiki page. We have a question about that.

Here is the result in wiki page.
![problem3b](https://cloud.githubusercontent.com/assets/19286702/15150218/e2662bde-16fe-11e6-8681-cbf7eac837b0.png)

Here is the result we got.
![problem3](https://cloud.githubusercontent.com/assets/19286702/15150081/65a92fa6-16fe-11e6-8320-d255c67c9942.png)

Two results agree but when separation goes beyond 4.5 micron, the force rises strangely. Do you think this a numerical error or not. 

Thanks in advance

**Comment by HomerReid** [comment]
Yes, this looks like a numerical artifact, which may be due to a couple of different sources. How does it vary with (a) mesh resolution, (b) unit-cell length, (c) the value of the `--RelTol` command-line argument?
distance s
I actually think the most likely culprit here is insufficient accuracy in the Xi (imaginary frequency) integration. You can increase this with the `--RelTol` command-line argument, which sets the relative tolerance for this integration. (The default is `--RelTol 1.0e-2`; you might try `--RelTol 1.0e-3`.) It would be useful to look at the Xi integrand (as reported in the `.byXi` output file) to see what the curves for different separation distances look like as functions of Xi; probably what is happening is that the integrand is being undersampled for d=5 um.
